nturtas/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('turtas.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

turtas/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import logout
from django.contrib.staticfiles.views import serve as serve_static
from django.views.decorators.cache import never_cache

from .views import (BuildingList, BuildingDetail, BuildingCreate, BuildingUpdate, BuildingDelete, BuildingBalance,
                    ClientList, ClientDetail, ClientCreate, ClientUpdate, ClientDelete, ApartmentList, ApartmentDetail,
                    ApartmentCreate, ApartmentUpdate, ApartmentDelete, LoanList, LoanDetail, LoanCreate, LoanUpdate,
                    LoanDelete, LoanSplit, BillList, BillDetail, BillCreate, BillUpdate, BillDelete, PaymentList,
                    PaymentDetail, PaymentCreate, PaymentUpdate, PaymentDelete, BillView, RepaymentSchedule,
                    RepaymentScheduleCombined, FineView, FineViewSB, ResetFine, CompensationCreate, CompensationView,
                    CompensationDelete, DocumentsView, LoanManagementView, ProfileView, CompensationUpdate)

urlpatterns = patterns('turtas.views',
    url(r'^login/$', 'login_user', name='login_user'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
    url(r'^$', 'home', name='home'),
    url(r'^buildings/$', BuildingList.as_view(), name='building_list'),
    url(r'^buildings/(?P<pk>[0-9]+)/$', BuildingDetail.as_view(), name='building_detail'),
    url(r'^buildings/new/$', BuildingCreate.as_view(), name='new_building'),
    url(r'^buildings/update/(?P<pk>[0-9]+)$', BuildingUpdate.as_view(), name='update_building'),
    url(r'^buildings/delete/(?P<pk>[0-9]+)$', BuildingDelete.as_view(), name='delete_building'),
    url(r'^buildings/balance/(?P<pk>[0-9]+)/$', BuildingBalance.as_view(), name='building_balance'),
    url(r'^clients/$', ClientList.as_view(), name='client_list'),
    url(r'^clients/(?P<pk>[0-9]+)/$', ClientDetail.as_view(), name='client_detail'),
    url(r'^clients/new/$', ClientCreate.as_view(), name='new_client'),
    url(r'^clients/update/(?P<pk>[0-9]+)$', ClientUpdate.as_view(), name='update_client'),
    url(r'^clients/delete/(?P<pk>[0-9]+)$', ClientDelete.as_view(), name='delete_client'),
    url(r'^apartments/$', ApartmentList.as_view(), name='apartment_list'),
    url(r'^apartments/(?P<pk>[0-9]+)/$', ApartmentDetail.as_view(), name='apartment_detail'),
    url(r'^apartments/new/$', ApartmentCreate.as_view(), name='new_apartment'),
    url(r'^apartments/update/(?P<pk>[0-9]+)$', ApartmentUpdate.as_view(), name='update_apartment'),
    url(r'^apartments/delete/(?P<pk>[0-9]+)$', ApartmentDelete.as_view(), name='delete_apartment'),
    url(r'^loans/$', LoanList.as_view(), name='loan_list'),
    url(r'^loans/(?P<pk>[0-9]+)/$', LoanDetail.as_view(), name='loan_detail'),
    url(r'^loans/new/$', LoanCreate.as_view(), name='new_loan'),
    url(r'^loans/update/(?P<pk>[0-9]+)$', LoanUpdate.as_view(), name='update_loan'),
    url(r'^loans/delete/(?P<pk>[0-9]+)$', LoanDelete.as_view(), name='delete_loan'),
    url(r'^loans/split/(?P<pk>[0-9]+)$', LoanSplit.as_view(), name='split_loan'),
    url(r'^loans/schedule/(?P<pk>[0-9]+)/$', RepaymentSchedule.as_view(), name='repayment_schedule'),
    url(r'^loans/schedule/(?P<type>[0-9]+)/(?P<pk>[0-9]+)/$', RepaymentScheduleCombined.as_view(),
        name='repayment_schedule_combined'),
    url(r'^bills/$', BillList.as_view(), name='bill_list'),
    url(r'^bills/(?P<pk>[0-9]+)/$', BillDetail.as_view(), name='bill_detail'),
    url(r'^bills/new/$', BillCreate.as_view(), name='new_bill'),
    url(r'^bills/update/(?P<pk>[0-9]+)$', BillUpdate.as_view(), name='update_bill'),
    url(r'^bills/delete/(?P<pk>[0-9]+)$', BillDelete.as_view(), name='delete_bill'),
    url(r'^payments/$', PaymentList.as_view(), name='payment_list'),
    url(r'^payments/(?P<pk>[0-9]+)/$', PaymentDetail.as_view(), name='payment_detail'),
    url(r'^payments/new/$', PaymentCreate.as_view(), name='new_payment'),
    url(r'^payments/update/(?P<pk>[0-9]+)$', PaymentUpdate.as_view(), name='update_payment'),
    url(r'^payments/delete/(?P<pk>[0-9]+)$', PaymentDelete.as_view(), name='delete_payment'),
    url(r'^bills/(?P<pk>[0-9]+)/generated/$', BillView.as_view(), name='bill_view'),
    url(r'^fines/$', FineView.as_view(), name='fines'),
    url(r'^fines-sb/$', FineViewSB.as_view(), name='fines_sb'),
    url(r'^reset-fine/(?P<pk>[0-9]+)$', ResetFine.as_view(), name='reset_fine'),
    url(r'^new_compensation/$', CompensationCreate.as_view(), name='new_compensation'),
    url(r'^compensations/$', CompensationView.as_view(), name='compensation_view'),
    url(r'^compensations/update/(?P<pk>[0-9]+)$', CompensationUpdate.as_view(), name='update_compensation'),
    url(r'^compensations/delete/(?P<pk>[0-9]+)$', CompensationDelete.as_view(), name='delete_compensation'),
    url(r'^documents/$', DocumentsView.as_view(), name='documents_view'),
    url(r'^loan-management/$', LoanManagementView.as_view(), name='loan_management'),
    url(r'^profile/(?P<pk>[0-9]+)$', ProfileView.as_view(), name='profile_view'),

    url(r'^static/(?P<path>.*)$', never_cache(serve_static)),
)

turtas/models.py
import calendar
import decimal
import math

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum

from .helpers import calculate_monthdelta, credit_balance_of_apartment, fine_list, credit_balance_of_loan, \
    create_repayment_schedule, calculate_compensation_sums, paid_early_amount_of_apartment


class UserExtended(models.Model):
    KELME = 'Kelme'
    TELSIAI = 'Telsiai'
    TYPE_OF_REPAYMENT_CALCULATION_CHOICES = (
        (KELME, KELME),
        (TELSIAI, TELSIAI)
    )
    user = models.OneToOneField(User)
    full_name = models.CharField(max_length=300, blank=True)
    ceo = models.CharField(max_length=300, blank=True)
    company_description = models.CharField(max_length=300, blank=True)
    company_description_short = models.CharField(max_length=300, blank=True)
    company_district = models.CharField(max_length=300, blank=True)
    bank = models.CharField(max_length=300, blank=True)
    bank_account = models.CharField(max_length=300, blank=True)
    # type_of_repayment_calculation = models.CharField(max_length=20, choices=TYPE_OF_REPAYMENT_CALCULATION_CHOICES,
    #                                                  default=TELSIAI)

    def __str__(self):
        return self.user.username


class Building(models.Model):
    added_by = models.ForeignKey(UserExtended, null=True, blank=True)
    name = models.CharField(max_length=300)
    floor_count = models.IntegerField()
    apartment_count = models.IntegerField()
    address = models.CharField(max_length=300)
    area = models.FloatField()
    description = models.TextField(blank=True)
    city = models.CharField(max_length=30, blank=True)
    renovation_finished_at = models.CharField(max_length=4, blank=True)
    district = models.CharField(max_length=30, blank=True)
    post_code = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=30, blank=True)
    extra_requisites = models.TextField(blank=True)
    invoice_note = models.TextField(blank=True)
    fine = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def paid_fines(self):
        return Payment.objects.filter(building=self, payment_type='3').aggregate(Sum('payment_sum')).payment_sum__sum

    def ongoing_fine(self):
        fine = fine_list(self)
        if len(fine) > 0:
            return fine[0]['fine']
        else:
            return 0


class Client(models.Model):
    added_by = models.ForeignKey(UserExtended, null=True, blank=True)
    name = models.CharField(max_length=300)
    client_type = models.CharField(max_length=30, blank=True)
    code = models.CharField(max_length=30, blank=True)
    telephone = models.CharField(max_length=10, blank=True)
    fax = models.CharField(max_length=10, blank=True)
    email = models.CharField(max_length=30, blank=True)
    description = models.TextField(blank=True)
    # buildings = models.ManyToManyField(Building, null=True, blank=True)
    reg_street = models.CharField(max_length=300, blank=True)
    reg_city = models.CharField(max_length=30, blank=True)
    reg_post_code = models.CharField(max_length=10, blank=True)
    reg_country = models.CharField(max_length=30, blank=True)
    corr_street = models.CharField(max_length=300, blank=True)
    corr_city = models.CharField(max_length=30, blank=True)
    corr_post_code = models.CharField(max_length=10, blank=True)
    corr_country = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class LoanType(models.Model):
    name = models.CharField(max_length=30)


class Apartment(models.Model):
    added_by = models.ForeignKey(UserExtended, null=True, blank=True)
    code = models.CharField(max_length=300)
    apartment_no = models.CharField(max_length=10, blank=True)
    area = models.FloatField()
    floor = models.CharField(max_length=2, blank=True)
    description = models.TextField(blank=True)
    building = models.ForeignKey(Building, null=True, blank=True)
    client = models.ForeignKey(Client, null=True, blank=True)
    own_funds = models.BooleanField(default=False)
    fine = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    overpaid = models.DecimalField(decimal_places=2, max_digits=10, default=0)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ['code']

    def get_loan_sum(self):
        loans = Loan.objects.filter(apartment=self)
        loan_sum = 0
        for loan in loans:
            loan_sum += loan.loan_sum
        return loan_sum

    def outstanding_loans_balance(self, date):
        loans = Loan.objects.filter(apartment=self)
        loan_sum = 0
        for loan in loans:
            loan_sum += loan.outstanding_loan_balance(date)
        return loan_sum

    def paid_fines(self):
        return Payment.objects.filter(apartment=self, payment_type='3').aggregate(Sum('payment_sum')).payment_sum__sum

    def ongoing_fine(self):
        fine = fine_list(apartment=self)
        if len(fine) > 0 and fine[0]['fine'] > 0:
            payments = self.payment_set.filter(payment_type=3)
            paid = 0
            for payment in payments:
                paid += payment.payment_sum
            return max(fine[0]['fine'] - paid, 0)
        else:
            return 0.00

    def current_fine(self):
        payments = self.payment_set.filter(payment_type=3)
        paid = 0
        for payment in payments:
            paid += payment.payment_sum
        return max(self.fine - paid, 0.00) or 0.00


class Loan(models.Model):
    added_by = models.ForeignKey(UserExtended, null=True, blank=True)
    contract_no = models.CharField(max_length=30)
    loan_type = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    building = models.ForeignKey(Building, null=True, blank=True)
    apartment = models.ForeignKey(Apartment, null=True, blank=True)
    loan_sum2 = models.DecimalField(decimal_places=2, max_digits=10, db_column='loan_sum', default=0)
    interest_rate = models.DecimalField(decimal_places=2, max_digits=5)
    currency = models.CharField(max_length=3)
    postponed_months = models.CharField(max_length=2, blank=True)
    loans = models.ForeignKey('self', null=True, blank=True)
    created_at = models.DateField(blank=True, null=True)
    valid_from = models.DateField(blank=True)
    valid_to = models.DateField(blank=True)
    accrued_interest = models.BooleanField(blank=True, default=False)
    payment_day = models.CharField(max_length=2, blank=True)
    days_interest_is_payable = models.IntegerField(default=365)
    calculate_fine = models.BooleanField(default=True)
    is_split = models.BooleanField(default=False)

    def __str__(self):
        return self.contract_no

    class Meta:
        ordering = ['apartment', 'building']

    def days_in_a_year(self, year):
        return self.days_interest_is_payable + 1 if calendar.isleap(year) else self.days_interest_is_payable

    @property
    def loan_sum(self):
        if self.accrued_interest:
            return self.loan_sum2
        else:
            return self.loan_sum2 - paid_early_amount_of_apartment(self.apartment if self.apartment else self.building)

    @property
    def number_of_periods(self):
        return calculate_monthdelta(self.valid_from, self.valid_to) - 1

    def monthly_payment(self, loan_sum, number_of_periods):
        # if self.building:
        try:
            return round(decimal.Decimal(math.ceil(loan_sum / (number_of_periods + 1) * 100) / 100), 2)  # KELME
        except:
            return 0
        # else:
        #     return round(decimal.Decimal(math.ceil(loan_sum / (number_of_periods + 1) * 100) / 100), 2)

    @property
    def monthly_payment_original(self):
        return self.monthly_payment(self.loan_sum, self.number_of_periods)

    def outstanding_loan_balance(self, date):
        return credit_balance_of_loan(self, date)


class Bill(models.Model):
    added_by = models.ForeignKey(UserExtended, null=True, blank=True)
    bill_no = models.CharField(max_length=300)
    building = models.ForeignKey(Building, null=True, blank=True)
    apartment = models.ForeignKey(Apartment, null=True, blank=True)
    client = models.ForeignKey(Client, null=True, blank=True)
    from_date = models.DateField()
    to_date = models.DateField()
    bill_sum = models.DecimalField(decimal_places=2, max_digits=10, blank=True)
    sent = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.bill_no

    class Meta:
        ordering = ['apartment']


class Payment(models.Model):
    added_by = models.ForeignKey(UserExtended, null=True, blank=True)
    name = models.CharField(max_length=300)
    apartment = models.ForeignKey(Apartment, null=True, blank=True)
    building = models.ForeignKey(Building, null=True, blank=True)
    payment_date = models.DateField(blank=True)
    # covered_date = models.DateField(blank=True)
    payment_type = models.CharField(max_length=300, null=True)
    payment_sum = models.DecimalField(decimal_places=2, max_digits=10, blank=True)
    currency = models.CharField(max_length=3, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    auto_id = models.CharField(max_length=36, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['apartment', '-payment_date']

    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     if self.apartment is not None:
    #         self.apartment.fine = self.apartment.ongoing_fine()
    #         self.apartment.save()
    #     elif self.building is not None:
    #         self.building.fine = self.building.ongoing_fine()
    #         self.building.save()

turtas/templates/client_actions.html
<div class="row">
	<div class="actions col-lg-6 col-lg-offset-3">
		<div class="btn-group btn-group-justified" role="group">
			<div class="btn-group" role="group">
	    		<button type="button" class="btn btn-primary" onclick="location.href='/clients/new/'"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Naujas Klientas</button>
	  		</div>
	  		<div class="btn-group" role="group">
	    		<button type="button" class="btn btn-primary" onclick="location.href='/clients/'"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Klientų sąrašas</button>
	  		</div>
	  		<div class="btn-group" role="group">
	    		<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-import" aria-hidden="true"></span> Importuoti</button>
	  		</div>
		</div>
	</div>
</div>

turtas/templates/client_detail.html
{% extends 'base.html' %}
{% block content %}
	<div class="col-lg-12">
		{% include 'client_actions.html' %}
        {% include 'messages.html' %}
	    <div class="col-lg-10 col-lg-offset-1">
	    <h2 class="">{{ object.name }}
            <a href="{% url 'update_client' object.pk %}" class="btn btn-default pull-right" role="button"><span class="glyphicon glyphicon-edit"></span> Redaguoti</a>
        </h2>
	    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
			<div class="panel panel-default">
		    	<div class="panel-heading" role="tab" id="headingOne">
		      		<h4 class="panel-title">
		        		<a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
		          			Bendra informacija
		        		</a>
		      		</h4>
		    	</div>
		    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
		     	<div class="panel-body">
			     	<div class="col-lg-6">
			        	<table class="table">
			        		<tbody>
			        			<tr>
			        				<th>Pavadinimas</th>
			        				<td>{{ object.name }}</td>
			        			</tr>
			        			<tr>
			        				<th>Tipas</th>
			        				<td>{{ object.client_type }}</td>
			        			</tr>
			        			<tr>
			        				<th>El. paštas</th>
			        				<td>{{ object.email }}</td>
			        			</tr>
			        			<tr>
			        				<th>Aprašymas</th>
			        				<td>{{ object.description }}</td>
			        			</tr>
			        			<tr>
			        				<th>Reg. adresas</th>
			        				<td>{{ object.reg_street }}<br>{{ object.reg_city }} {{ object.reg_post_code }}<br>{{ object.reg_country }}</td>
			        			</tr>
			        		</tbody>
			        	</table>
			        </div>
			        <div class="col-lg-6">
			        	<table class="table">
			        		<tbody>
			        			<tr>
			        				<th>Kodas</th>
			        				<td>{{ object.code|default_if_none:"" }}</td>
			        			</tr>
			        			<tr>
			        				<th>Telefonas</th>
			        				<td>{{ object.telephone }}</td>
			        			</tr>
			        			<tr>
			        				<th>Faksas</th>
			        				<td>{{ object.fax }}</td>
			        			</tr>
			        			<tr>
			        				<th>Koresp. adresas</th>
			        				<td>{{ object.corr_street }}<br>{{ object.corr_city }} {{ object.corr_post_code }}<br>{{ object.corr_country }}</td>
			        			</tr>
			        		</tbody>
			        	</table>
			        </div>
		      	</div>
		    </div>
		</div>

		<div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="headingTwo">
		      	<h4 class="panel-title">
		      		<a class="collapsed" role="button" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
		        		Butai
		        	</a>
		      	</h4>
		    </div>
		    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
		      	<div class="panel-body">
		       		<table class="table table-striped table-hover tablesorter">
				    	<thead>
					    	<tr>
					    		<th>Kodas</th>
					    		<th>Buto Nr.</th>
					    		<th>Klientas</th>
					    		<th>Pastatas</th>
					    		<th>Plotas</th>
					    		<th>Nuosavos lėšos</th>
					    		<th>Įvedė</th>
					    	</tr>
				    	</thead>
				    	<tbody>
					        {% for apartment in object.apartment_set.all %}
					        	<tr class='clickable-row' data-href='/apartments/{{ apartment.pk }}'>
					            	<td>{{ apartment.code }}</td>
					            	<td>{{ apartment.apartment_no }}</td>
					            	<td>{{ apartment.client.name }}</td>
					            	<td>{{ apartment.building.name }}</td>
					            	<td>{{ apartment.area }}</td>
					            	<td>{{ apartment.own_funds }}</td>
					            	<td>{{ apartment.added_by }}</td>
					            </tr>
					        {% endfor %}
				        </tbody>
				    </table>
		      	</div>
		    </div>
		</div>

		<div class="panel panel-default">
{#		    <div class="panel-heading" role="tab" id="headingFour">#}
{#		      	<h4 class="panel-title">#}
{#		      		<a class="collapsed" role="button" data-toggle="collapse" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">#}
{#		        		Sąskaitos#}
{#		        	</a>#}
{#		      	</h4>#}
{#		    </div>#}
		    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
		      	<div class="panel-body">
			       	<table class="table table-striped table-hover tablesorter table-condensed">
		    	<thead>
			    	<tr>
			    		<th></th>
			    		<th>Sąskaitos Nr.</th>
			    		<th>Pastatas</th>
			    		<th>Butas</th>
			    		<th>Klientas</th>
			    		<th>Nuo</th>
			    		<th>Iki</th>
			    		<th>Suma</th>
			    		<th>Išsiųsta</th>
			    		<th>Įvedė</th>
			    	</tr>
		    	</thead>
		    	<tbody>
			        {% for bill in client.bill_set.all %}
			        	<tr class='clickable-row' data-href='/bills/{{ bill.pk }}'>
			        		<td><a href=""><span class="glyphicon glyphicon-edit"></span></a></td>
			            	<td>{{ bill.bill_no }}</td>
			            	<td>{{ bill.building }}</td>
			            	<td>{{ bill.apartment }}</td>
			            	<td>{{ bill.client }}</td>
			            	<td>{{ bill.from_date }}</td>
			            	<td>{{ bill.to_date }}</td>
			            	<td>{{ bill.bill_sum }}</td>
			            	<td>{{ bill.sent }}</td>
			            	<td>{{ bill.added_by }}</td>
			            </tr>
			        {% endfor %}
		        </tbody>
		    </table>
		      	</div>
		    </div>
		</div>
	</div>
	</div>
{% endblock %}

turtas/templates/new_apartment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
	<!-- <link href="{% static 'css/new_client.css' %}" rel="stylesheet"> -->
	<script src="{% static 'js/new_apartment.js' %}"></script>
{% endblock %}
{% block content %}
	<div class="col-lg-12">
		{% include 'apartment_actions.html' %}

		<div class="row col-lg-10 col-lg-offset-1 panel panel-default">
			<h2 class="new-building-title page-header">Naujas Butas</h2>
			{% csrf_token %}
			<form class="form-horizontal building-form" action="{% url 'new_apartment' %}?next={{ request.META.HTTP_REFERER }}" method="post">
	  			<div class="form-group row">
	    			<label for="code" class="col-lg-2 control-label">Kodas <span class="asterisk">*</span></label>
					<div class="col-lg-4 form-group">
	  					<input class="form-control" id="code" name="code" placeholder="Kodas" required>
					</div>
					<label for="building" class="col-lg-2 control-label">Pastatas</label>
					<div class="col-lg-4 form-group">
	  					<select class="form-control selectpicker" id="building" name="building" data-live-search="true">
	  						<option value="">Pasirinkite</option>
	  						{% for building in buildings %}
	  							<option value="{{ building.pk }}">{{ building.name }}</option>
	  						{% endfor %}
	  					</select>
					</div>
	  			</div>
	  			<div class="form-group row">
	    			<label for="apartment_no" class="col-lg-2 control-label">Buto nr.</label>
					<div class="col-lg-4 form-group">
	  					<input class="form-control" id="apartment_no" name="apartment_no" placeholder="Buto nr.">
					</div>
					<label for="client" class="col-lg-2 control-label">Klientas</label>
					<div class="col-lg-4 form-group">
	  					<select class="form-control selectpicker" id="client" name="client" data-live-search="true">
		  					<option value="">Pasirinkite</option>
		  					{% for client in clients %}
	  							<option value="{{ client.pk }}">{{ client.name }}</option>
	  						{% endfor %}	
  						</select>
					</div>
	  			</div>
	  			<div class="form-group row">
	    			<label for="area" class="col-lg-2 control-label">Plotas<span class="asterisk">*</span></label>
					<div class="col-lg-4 form-group">
	  					<input class="form-control" id="area" name="area" placeholder="Plotas">
					</div>
					<label for="own_funds" class="col-lg-2 control-label">Nuosavos lėšos</label>
					<div class="col-lg-4 form-group">
	  					<input type="checkbox" class="form-control" id="own_funds" name="own_funds">
					</div>
	  			</div>
	  			<div class="form-group row">
	    			<label for="floor" class="col-lg-2 control-label">Aukštas</label>
					<div class="col-lg-4 form-group">
	  					<input class="form-control" id="floor" name="floor" placeholder="Aukštas">
					</div>
					<label for="description" class="col-lg-2 control-label">Aprašymas</label>
					<div class="col-lg-4 form-group">
	  					<textarea class="form-control" id="description" name="description" rows="3"></textarea>
					</div>
	  			</div>	  			  			
	  			<div class="col-lg-6">
  					<button class="btn btn-primary btn-lg btn-block new-building-button">Išsaugoti</button>	
	  			</div>	  			
			</form>
			
  			<div class="col-lg-6">
  				<button class="btn btn-default btn-lg btn-block new-building-button new-building-cancel" onclick="location.href='/apartments/'">Atšaukti</button>	
  			</div>	
		</div>
	</div>
{% endblock %}

turtas/templates/payment_actions.html
<div class="row">
	<div class="actions col-lg-6 col-lg-offset-3">
		<div class="btn-group btn-group-justified" role="group">
			<div class="btn-group" role="group">
	    		<button type="button" class="btn btn-primary" onclick="location.href='/payments/new/'"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Naujas mokėjimas</button>
	  		</div>
	  		<div class="btn-group" role="group">
	    		<button type="button" class="btn btn-primary" onclick="location.href='/payments/'"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Mokėjimų sąrašas</button>
	  		</div>
	  		<div class="btn-group" role="group">
	    		<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-import" aria-hidden="true"></span> Importuoti</button>
	  		</div>
		</div>
	</div>
</div>